DROP TABLE IF EXISTS champion CASCADE;

CREATE TABLE champion (
	id INT AUTO_INCREMENT NOT NULL,
	season INT NOT NULL,
	winner VARCHAR(255) NOT NULL,
	nation VARCHAR(255) NOT NULL,
    team VARCHAR(255) NOT NULL,
	PRIMARY KEY(id)
);